#define BLACK             "\e[30m"
#define RED               "\e[31m"
#define GREEN             "\e[32m"
#define YELLOW            "\e[33m"
#define BLUE              "\e[34m"
#define MAGENTA           "\e[35m"
#define CYAN              "\e[36m"
#define WHITE             "\e[37m"

#define BRIGHT_BLACK      "\e[90m"
#define BRIGHT_RED        "\e[91m"
#define BRIGHT_GREEN      "\e[92m"
#define BRIGHT_YELLOW     "\e[93m"
#define BRIGHT_BLUE       "\e[94m"
#define BRIGHT_MAGENTA    "\e[95m"
#define BRIGHT_CYAN       "\e[96m"
#define BRIGHT_WHITE      "\e[97m"

#define BOLD              "\e[1m"
#define FAINT             "\e[2m"
#define ITALIC            "\e[3m"
#define UNDERLINE         "\e[4m"

#define DISABLE_BOLD      "\e[21m"
#define DISABLE_FAINT     "\e[22m"
#define DISABLE_ITALIC    "\e[23m"
#define DISABLE_UNDERLINE "\e[24m"

#define RESET             "\e[0m"
